name: Full Deploy Node.js App to Azure Web App - ecss-backend-node-backup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (Stable LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies and build app
        run: |
          cd backend
          npm ci
          npm run build --if-present

      - name: Create deployment ZIP (Full Deployment)
        run: |
          cd backend
          zip -r -q ../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App (Full Clean Deployment)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-node-backup'
          slot-name: 'Production'
          package: release.zip
          clean: true  # 🚀 Ensures a full fresh deployment

      - name: Set Azure App Settings for Fast ZIP Deployment
        uses: azure/appservice-settings@v1
        with:
          app-name: 'ecss-backend-node-backup'
          app-settings-json: |
            [
              {"name": "WEBSITE_RUN_FROM_PACKAGE", "value": "1"}
            ]
