name: ECSS Backend Side - Node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
      id-token: write  # This is required for requesting the JWT
    environment:
      name: 'Production'

    steps:
      - uses: actions/checkout@v4

      - name: Check if any deployment is in progress
        id: check_deployment_status
        run: |
          echo "Checking if a deployment is already in progress..."
          
          # Log in to Azure if necessary
          az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5AB7D5C3556C4887A1D6861E627F89F7 }}
          
          # Get the deployment status
          DEPLOYMENT_STATUS=$(az webapp deployment list \
            --name 'ecss-backend-node' \
            --resource-group 'ECSS-Course-Management-System' \
            --query "[?status=='InProgress'].status" -o tsv)
          
          if [ "$DEPLOYMENT_STATUS" == "InProgress" ]; then
            echo "A deployment is already in progress. Exiting early."
            exit 0  # Exit early if a deployment is in progress
          else
            echo "No deployment is in progress. Proceeding with the build and deploy."
          fi
    
      # Fetch previous commit (before push) only if no deployment is in progress
      - name: Fetch previous commit (before push)
        if: ${{ steps.check_deployment_status.outcome != 'failure' }}  # Proceed only if no deployment is in progress
        run: |
          git fetch origin main --depth=2
          echo "Before push commit:"
          git log --oneline -n 2  # Show the last 2 commits

      - name: Check for changes in the backend folder between before and after push
        id: check_changes
        run: |
          echo "Checking for changes in the backend folder between before and after push..."
  
          # Ensure we fetch the previous commit to compare against
          git fetch origin main --depth=2  # Fetch the last 2 commits

          # Use git diff to directly compare the previous commit (HEAD^) and the current commit (HEAD), 
          # limiting the diff to the backend folder
          CHANGES=$(git diff --name-only HEAD~1 HEAD -- backend/)

          # Check if changes are detected in the backend folder
          if [ -z "$CHANGES" ]; then
            echo "No changes detected in the backend folder. Skipping build and deploy."
            echo "::set-output name=changes_detected::false"
            exit 0  # Exit early if no changes are detected
          else
            echo "Changes detected in the backend folder. Proceeding with build and deploy."
            echo "::set-output name=changes_detected::true"
          fi

      - name: Debug changes detected
        run: 'echo "Changes detected: ${{ steps.check_changes.outputs.changes_detected }}"'

      - name: Set up Node.js version
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  # Deploy only if changes were detected
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  # Deploy only if changes were detected
        run: |
          cd backend
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifact for deployment (only backend folder)
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  # Deploy only if changes were detected
        run: |
          cd backend
          zip -r ../release.zip .  # Create zip file

      - name: Upload artifact for deployment
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  # Deploy only if changes were detected
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Login to Azure
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  # Deploy only if changes were detected
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_41A26900721847DFB378D91324F04C5C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F80B66AC3E847918F02B61E622A3768 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5AB7D5C3556C4887A1D6861E627F89F7 }}

      # Only proceed with deployment if changes are detected in the backend folder
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  # Deploy only if changes were detected
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-node'
          slot-name: 'Production'
          package: ./release.zip  # Use the zip file created from the backend folder

      - name: Ensure deployment continues in background
        run: |
          echo "Deployment started. This will continue in the background."
          exit 0  # Ensures job ends successfully after deployment
