name: Build and deploy Node.js app to Azure Web App - ecss-backend-node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifact for deployment (only backend folder)
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  check:
    runs-on: ubuntu-latest
    needs: build # Ensure that the build job only runs after the check job is complete
    permissions:
      contents: read  # This is required for actions/checkout
    if: ${{ success() }}  # Run build only if changes are detected

    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest changes from origin
        run: |
          # Fetch the latest changes from the main branch
          git fetch origin main

      - name: Check if there are any changes in the backend directory
        id: check-changes
        run: |
          # Check for changes in the backend directory between current branch and main branch
          git diff --exit-code origin/main -- backend
          if [ $? -eq 0 ]; then
            echo "No changes detected in backend. Skipping build and deployment."
            echo "::set-output name=changes_detected::false"
            exit 0  # Exit successfully if no changes are detected
          else
            echo "Changes detected in backend. Proceeding with build and deployment."
            echo "::set-output name=changes_detected::true"
          fi      

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that deploy only runs after build is completed
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    if: ${{ needs.check.outputs.changes_detected == 'true' }}  # Ensure deploy only runs if changes are detected and build is successful

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_41A26900721847DFB378D91324F04C5C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F80B66AC3E847918F02B61E622A3768 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5AB7D5C3556C4887A1D6861E627F89F7 }}

      - name: Deploy to Azure Web App (without incremental checks)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-node'
          slot-name: 'Production'
          package: .

      # Optional: You can keep this step for logging purposes if needed
      - name: Ensure deployment continues in background
        run: |
          echo "Deployment started. This will continue in the background."
