name: ECSS Backend Django

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write  # Required for Azure login

    environment:
      name: 'Production'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compare the current and previous commit for specific folders and files
        id: compare_commits
        run: |
          # Get the previous commit ID
          previous_commit=$(git rev-parse HEAD~1)

          # Define the paths to monitor for changes
          paths="djangoPython requirements.txt venv"

          # Compare the repository between the current and previous commit for specific paths
          echo "Comparing the repository for changes in djangoPython, requirements.txt, and venv folders"
          changes=$(git diff --name-only $previous_commit HEAD -- $paths)

          if [ -z "$changes" ]; then
            echo "No changes detected in specified paths, skipping deployment."
            echo "::set-output name=deploy::false"
          else
            echo "Changes detected in specified paths, proceeding with deployment."
            echo "::set-output name=deploy::true"
          fi

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        if: steps.compare_commits.outputs.deploy == 'true'

      - name: Install dependencies
        run: pip install -r requirements.txt
        if: steps.compare_commits.outputs.deploy == 'true'

      - name: Zip artifact for deployment
        run: zip -r release.zip djangoPython -x "djangoPython/venv/*"
        if: steps.compare_commits.outputs.deploy == 'true'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01E6C8A212504569A3E418BCCCBB0947 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF53037E7A2840779D7BBBA99B205BD1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F754611B88D7432FA2F0EBA31E894E04 }}
        if: steps.compare_commits.outputs.deploy == 'true'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ecss-backend-django-backup'
          slot-name: 'Production'
          package: release.zip
        if: steps.compare_commits.outputs.deploy == 'true'
